### ISSUE TITLE
Is there a way to make Java classes internal?

### ISSUE THREAD

**Issue by szadev** [joniles/MPXJ.Net#18]
Is there a way to make Java classes internal?
Visual Studio suggests a lot of Java types in every part of the project, which makes development difficult.

**Comment by joniles** [comment]
Ideally I'd like to be able to make the dependencies of `MPXJ.Net` NuGet package private, or at least be able to tell Intellisense not to suggest from certain assemblies... but neither of those things seems to be possible at the moment. The closest I've come is to update the Intellisense settings for C# (Tools->Options->C#->Intellisense) to disable suggesting from unimported namespaces:

![image](https://github.com/user-attachments/assets/9e7de2fc-accc-44c4-b451-90b5153e9c85)
